version: '3.3'

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    ports:
      # Puerto para el panel web de configuración inicial (Setup)
      - "3000:3000/tcp"
      # Puerto para el servicio DNS (el más importante y el que usaremos)
      - "53:53/tcp"
      - "53:53/udp"
      # (Opcional) Puerto para el panel web final, si quieres que esté en el puerto 80
      - "80:80/tcp"
    volumes:
      # Persistencia de datos. 'work' y 'conf' son las carpetas que creamos antes
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
